// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-tRf63-t-4wbCUZpB21F1frA81Yi-bw',
    appId: '1:880914266003:android:9c544fcbe91b9d842e5a66',
    messagingSenderId: '880914266003',
    projectId: 'licenta-ead67',
    storageBucket: 'licenta-ead67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRIfhhTAEVtdwPuxpc8S74GLoWWN7sBD4',
    appId: '1:880914266003:ios:02ecc269a936a3492e5a66',
    messagingSenderId: '880914266003',
    projectId: 'licenta-ead67',
    storageBucket: 'licenta-ead67.appspot.com',
    iosClientId: '880914266003-sgajl2tev9nc6iq8rle71gp9g97ij84f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceta',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5tbpDhEXV-Gnx7hwA15UbiUYh5d0LmxM',
    appId: '1:880914266003:web:311476bfba51d6332e5a66',
    messagingSenderId: '880914266003',
    projectId: 'licenta-ead67',
    authDomain: 'licenta-ead67.firebaseapp.com',
    storageBucket: 'licenta-ead67.appspot.com',
    measurementId: 'G-2WRVWFJJTS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRIfhhTAEVtdwPuxpc8S74GLoWWN7sBD4',
    appId: '1:880914266003:ios:02ecc269a936a3492e5a66',
    messagingSenderId: '880914266003',
    projectId: 'licenta-ead67',
    storageBucket: 'licenta-ead67.appspot.com',
    iosClientId: '880914266003-sgajl2tev9nc6iq8rle71gp9g97ij84f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5tbpDhEXV-Gnx7hwA15UbiUYh5d0LmxM',
    appId: '1:880914266003:web:311476bfba51d6332e5a66',
    messagingSenderId: '880914266003',
    projectId: 'licenta-ead67',
    authDomain: 'licenta-ead67.firebaseapp.com',
    storageBucket: 'licenta-ead67.appspot.com',
    measurementId: 'G-2WRVWFJJTS',
  );

}